#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other shells available, try using one of them.
#   (2) Gradle will create wrapper files in ~/.gradle by default, but you can also
#       specify an alternate location for wrapper files via --gradle-user-home
#       option.
#   (3) The wrapper is only used if gradlew or gradlew.bat is available.
#   (4) Change the evaluation of DEFAULT_JVM_OPTS, CLASSPATH, JAVA_OPTS and GRADLE_OPTS below as needed,
#       depending on your machine configuration.
#
# See the Gradle FAQ at https://gradle.org/faq
#
##############################################################################

PROG="$0"
while [ -h "$PROG" ] ; do
    ls=`ls -ld "$PROG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PROG="$link"
    else
        PROG=`dirname "$PROG"`/"$link"
    fi
done

SAVED="`pwd`"
cd "`dirname \"$PROG\"`" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='\"$@\"'

# Use the maximum available, or set MAX_FD != maximum if you use "ulimit -n" to set the open file descriptor limit.
if [ "$MAX_FD" = "maximum" ] || [ "$MAX_FD" = "max" ] ; then
    MAX_FD="`ulimit -H -n`"
fi
if [ -z "$MAX_FD" ] || [ "$MAX_FD" = "unlimited" ] ; then
    MAX_FD="262144"
fi
ulimit -n $MAX_FD

QUOTE_ARGS=""
for arg in "$@" ; do
    QUOTE_ARG="`printf '%s\n' "$arg" | sed \"s/[']/'\\\\''/g\"`"
    QUOTE_ARGS="$QUOTE_ARGS '$QUOTE_ARG'"
done

eval "exec \"$JAVACMD\" $DEFAULT_JVM_OPTS -classpath \"$CLASSPATH\" org.gradle.wrapper.GradleWrapperMain $QUOTE_ARGS"
