#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other shells available, try using one of them.
#   (2) Gradle will create wrapper files in ~/.gradle by default, but you can also
#       specify an alternate location for wrapper files via --gradle-user-home
#       option.
#   (3) The wrapper is only used if gradlew or gradlew.bat is available.
#   (4) Change the evaluation of DEFAULT_JVM_OPTS, CLASSPATH, JAVA_OPTS and GRADLE_OPTS below as needed,
#       depending on your machine configuration.
#
# See the Gradle FAQ at https://gradle.org/faq
#
##############################################################################

PROG="$0"
# Determine the directory in which a script resides
PROG_DIR=""
case "$PROG" in
  */*/*/gradlew )
    # Parse PROG to determine directory
    PROG_DIR=`echo "$PROG" | sed 's|\(.*\)/[^/]*$|\1|'`
    ;;
  */*gradlew )
    PROG_DIR=`echo "$PROG" | sed 's|\(.*\)/[^/]*$|\1|'`
    ;;
  gradlew )
    PROG_DIR="."
    ;;
esac

# A function to find the awk executable, since the one in /bin/gawk is often not the same awk that is in PATH
FIND_AWK() {
    if command -v gawk &> /dev/null; then
        echo "gawk"
    elif command -v awk &> /dev/null; then
        echo "awk"
    else
        echo ""
    fi
}

# Try to determine APP_HOME
try_symlink() {
    if [ -h "$1" ] 2>/dev/null; then
        ls -ld "$1" 2>/dev/null | sed 's/ -> .*//' | sed 's/^.* //'
    fi
}

APP_HOME=`cd "$(dirname "$0")" && pwd`

# A temporary variable for the script dir
SCRIPT_DIR="$( cd "${PROG_DIR}" && pwd )"

# Escape application home
quoted_app_home=$(printf '%s\n' "$APP_HOME" | sed 's| |\\|g')

# Use double quotes to make variables substitution resilient to any kind of quoting mechanism used by the shell.
quoted_java_home=$(printf '%s\n' "$JAVA_HOME" | sed 's| |\\|g')

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $( ulimit -S -n ) in #(
      open)                           # Not possible
        ;; #(
      [\\\!]*[0-9]*) #(
        if [ -w /proc/sys/fs/file-max ]; then
          . /proc/sys/fs/file-max
          MAX_FD=$((MAX_FD < 999999 ? 999999 : MAX_FD))
          echo "Setting MAX_FD to $MAX_FD"
          ulimit -n $MAX_FD
        fi
        ;; #(
      *)
        MAX_FD=$((\$MAX_FD < 999999 ? 999999 : \$MAX_FD))
        ulimit -n $MAX_FD
        ;;
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

set -- \
        -Dorg.gradle.appname=$APP_BASE_NAME \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" has processed all arguments
eval "set -- $(printf '%s\\n' "${DEFAULT_JVM_OPTS} ${JAVA_OPTS} ${GRADLE_OPTS}" | xargs -n1 printf ' \"%%s\"\n' | tr '\n' ' ')" "$@"

# by default we should be in the correct project dir, but when run from Finder on Mac, the cwd is wrong
if [ "$(uname)" = "Darwin" ] && [ "$HOME" = "$PWD" ]; then
  cd "$(dirname "$0")"
fi

exec "$JAVACMD" "$@"
